{{ config(materialized='table') }}

SELECT
    TRANSACTION_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    PRODUCT_SKU,
    QUANTITY,
    UNIT_PRICE,
    CAST(QUANTITY * UNIT_PRICE AS DECIMAL(10,2)) AS SALES_AMOUNT,
    PAYMENT_DATE,
    PAYMENT_METHOD
FROM {{ ref('int_orders') }}


