{{ config(materialized='view') }}

WITH deduped_database_orders AS (
    SELECT DISTINCT
        ORDER_DATE,
        ORDER_NUMBER,
        BILLING_NAME,
        ADDRESS_COMPANY,
        ADDRESS_CITY,
        ADDRESS_PROVINCE,
        ADDRESS_ZIP,
        PHONE,
        EMAIL,
        LINEITEM_NAME,
        LINEITEM_QTY,
        PRODUCT_CATEGORY,
        PRODUCT_DESCRIPTION,
        PRODUCT_SKU,
        UNIT_PRICE,
        VENDOR,
        IMAGE_SRC,
        FULFILLMENT_DATE,
        PAYMENT_DATE,
        PAYMENT_METHOD,
        PAYMENT_REFERENCE
    FROM {{ source('raw_data', 'database_orders') }}
)

SELECT
    -- Order Identifier
    CAST(UPPER(SUBSTR(MD5(ORDER_DATE || BILLING_NAME || LINEITEM_NAME || PAYMENT_DATE || LINEITEM_QTY), 1, 12)) AS STRING) AS TRANSACTION_ID,
    CAST(ORDER_NUMBER AS STRING) AS ORDER_NUMBER,
    -- Customer Information
    CAST(BILLING_NAME AS STRING) AS CUSTOMER_NAME,
    CAST(ADDRESS_COMPANY AS STRING) AS STREET_ADDRESS,
    CAST(ADDRESS_CITY AS STRING) AS CITY,
    CAST(ADDRESS_PROVINCE AS STRING) AS PROVINCE,
    CAST(ADDRESS_ZIP AS STRING) AS ZIP,
    CAST(PHONE AS STRING) AS PHONE,
    CAST(EMAIL AS STRING) AS EMAIL,
    -- Product Information
    CAST(LINEITEM_NAME AS STRING) AS PRODUCT_NAME,
    CAST(LINEITEM_QTY AS INTEGER) AS QUANTITY,
    CAST(PRODUCT_CATEGORY AS STRING) AS PRODUCT_CATEGORY,
    CAST(PRODUCT_DESCRIPTION AS STRING) AS PRODUCT_DESCRIPTION,
    CAST(PRODUCT_SKU AS STRING) AS PRODUCT_SKU,
    CAST(UNIT_PRICE AS DECIMAL(10,2)) AS UNIT_PRICE,
    CAST(VENDOR AS STRING) AS VENDOR,
    CAST(IMAGE_SRC AS STRING) AS IMAGE_SRC,
    -- Transaction Dates
    CAST(ORDER_DATE AS TIMESTAMP_NTZ) AS ORDER_DATE,
    CAST(FULFILLMENT_DATE AS TIMESTAMP_NTZ) AS FULFILLMENT_DATE,
    CAST(PAYMENT_DATE AS TIMESTAMP_NTZ) AS PAYMENT_DATE,
    -- Payment Information
    CAST(PAYMENT_METHOD AS STRING) AS PAYMENT_METHOD,
    CAST(PAYMENT_REFERENCE AS STRING) AS PAYMENT_REFERENCE
FROM deduped_database_orders

/*
Limit rows to 100 for test/development runs only
Delete or comment out for production
*/

-- {% if var('is_test_run', default=true) %}

--   limit 100

-- {% endif %}