FROM apache/airflow:3.1.3-python3.10

USER root

RUN apt-get update && \
    apt-get -y install git && \
    apt-get clean

ENV PYTHONPATH="/opt/airflow/plugins:${PYTHONPATH}"

USER airflow

# Install provider packages from requirements.txt
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt
# RUN pip install -r /tmp/requirements.txt