{{ config(materialized='view') }}

SELECT
    CAST(UPPER(SUBSTR(MD5(FULL_NAME || ADDRESS_COMPANY), 1, 8)) AS STRING) AS CUSTOMER_ID,
    CAST(FULL_NAME AS STRING) AS CUSTOMER_NAME,
    CAST(FIRST_NAME AS STRING) AS FIRST_NAME,
    CAST(LAST_NAME AS STRING) AS LAST_NAME,
    CAST(EMAIL AS STRING) AS EMAIL,
    CAST(ADDRESS_COMPANY AS STRING) AS STREET_ADDRESS,
    CAST(ADDRESS_CITY AS STRING) AS CITY,
    CAST(ADDRESS_PROVINCE AS STRING) AS PROVINCE,
    CAST(ADDRESS_ZIP AS STRING) AS ZIP,
    CAST(PHONE AS STRING) AS PHONE
FROM {{ source('raw_data', 'customers') }}
