{{ config(materialized='view') }}

SELECT
    CAST(PRODUCT_SKU AS STRING) AS PRODUCT_SKU,
    CAST(TITLE AS STRING) AS PRODUCT_NAME,
    CAST(PRODUCT_DESCRIPTION AS STRING) AS PRODUCT_DESCRIPTION,
    CAST(PRODUCT_CATEGORY AS STRING) AS PRODUCT_CATEGORY,
    CAST(VENDOR AS STRING) AS VENDOR,
    CAST(UNIT_PRICE AS DECIMAL(10,2)) AS UNIT_PRICE,
    CAST(IMAGE_SRC AS STRING) AS IMAGE_SRC
FROM {{ source('raw_data', 'products') }}
