{{ config(materialized='table') }}

SELECT
    IO.ORDER_DATE, IP.PRODUCT_NAME, IP.PRODUCT_DESCRIPTION, IP.PRODUCT_CATEGORY,
    IP.VENDOR, IP.IMAGE_SRC, IC.FIRST_NAME, IC.LAST_NAME, IC.CUSTOMER_NAME,
    IC.EMAIL, IC.STREET_ADDRESS, IC.CITY, IC.LATITUDE, IC.LONGITUDE,
    IC.PROVINCE, IC.ZIP, IC.PHONE, IO.QUANTITY, IO.UNIT_PRICE,
    IO.PAYMENT_DATE, IO.PAYMENT_METHOD, IO.DATASOURCE
FROM    {{ ref('int_orders') }} IO

LEFT JOIN   {{ ref('int_customers') }} IC
    ON IC.CUSTOMER_ID = IO.CUSTOMER_ID
    
LEFT JOIN   {{ ref('int_products') }} IP
    ON IP.PRODUCT_SKU = IO.PRODUCT_SKU
    