{{ config(materialized='table') }}

WITH ORDERS AS (
    SELECT
        IP.PRODUCT_CATEGORY,
        IO.ORDER_DATE,
        IO.QUANTITY,
        IO.UNIT_PRICE
    FROM    {{ ref('int_orders') }} IO
    LEFT JOIN   {{ ref('int_products') }} IP
    ON  IO.PRODUCT_SKU = IP.PRODUCT_SKU
)

SELECT
    YEAR(ORDER_DATE) AS ORDER_YEAR,
    PRODUCT_CATEGORY,
    CASE MONTH(ORDER_DATE)
        WHEN 1  THEN 'JAN'
        WHEN 2  THEN 'FEB'
        WHEN 3  THEN 'MAR'
        WHEN 4  THEN 'APR'
        WHEN 5  THEN 'MAY'
        WHEN 6  THEN 'JUN'
        WHEN 7  THEN 'JUL'
        WHEN 8  THEN 'AUG'
        WHEN 9  THEN 'SEP'
        WHEN 10 THEN 'OCT'
        WHEN 11 THEN 'NOV'
        WHEN 12 THEN 'DEC'
    ELSE NULL
    END AS ORDER_MONTH,
        
    SUM(QUANTITY) AS UNITS_SOLD,
    SUM(QUANTITY*UNIT_PRICE) AS SALES
FROM    ORDERS
GROUP BY    YEAR(ORDER_DATE), PRODUCT_CATEGORY, MONTH(ORDER_DATE)
ORDER BY    YEAR(ORDER_DATE), PRODUCT_CATEGORY, MONTH(ORDER_DATE)