{{ config(materialized='table') }}

WITH ORDERS AS (
    SELECT
        IP.PRODUCT_CATEGORY,
        IO.ORDER_DATE,
        IO.QUANTITY,
        IO.UNIT_PRICE
    FROM    {{ ref('int_orders') }} IO
    LEFT JOIN   {{ ref('int_products') }} IP
    ON  IO.PRODUCT_SKU = IP.PRODUCT_SKU
),
MONTHLY_SUMMARY AS (
    SELECT
        YEAR(ORDER_DATE) AS ORDER_YEAR,
        PRODUCT_CATEGORY,
        MONTH(ORDER_DATE) AS ORDER_MONTH_NUM,
        CASE MONTH(ORDER_DATE)
            WHEN 1  THEN 'JAN'
            WHEN 2  THEN 'FEB'
            WHEN 3  THEN 'MAR'
            WHEN 4  THEN 'APR'
            WHEN 5  THEN 'MAY'
            WHEN 6  THEN 'JUN'
            WHEN 7  THEN 'JUL'
            WHEN 8  THEN 'AUG'
            WHEN 9  THEN 'SEP'
            WHEN 10 THEN 'OCT'
            WHEN 11 THEN 'NOV'
            WHEN 12 THEN 'DEC'
        ELSE NULL
        END AS ORDER_MONTH,
            
        SUM(QUANTITY) AS UNITS_SOLD,
        SUM(QUANTITY*UNIT_PRICE) AS SALES
    FROM    ORDERS
    GROUP BY    PRODUCT_CATEGORY, YEAR(ORDER_DATE), MONTH(ORDER_DATE)
    ORDER BY    PRODUCT_CATEGORY, YEAR(ORDER_DATE)
)
SELECT
    ROW_NUMBER() OVER (ORDER BY ORDER_YEAR, PRODUCT_CATEGORY, ORDER_MONTH_NUM) AS ROW_NUM,
    ORDER_YEAR,
    PRODUCT_CATEGORY,
    ORDER_MONTH,
    SUM(UNITS_SOLD) OVER (
        PARTITION BY PRODUCT_CATEGORY
        ORDER BY PRODUCT_CATEGORY
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS RUNNING_TOTAL_UNITS_SOLD,
    SUM(SALES) OVER(
        PARTITION BY PRODUCT_CATEGORY
        ORDER BY PRODUCT_CATEGORY
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS RUNNIG_TOTAL_SALES
FROM MONTHLY_SUMMARY
ORDER BY ROW_NUM