-- Switch to database
USE DATABASE ECOMM_DB;
USE SCHEMA ECOMM;

CREATE OR REPLACE FILE FORMAT QUOTE_ALL
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE STAGE MY_GCS_STAGE
    STORAGE_INTEGRATION = MY_GCS_INTEGRATION
    URL = 'gcs://bucket_ecomm/'
    FILE_FORMAT = QUOTE_ALL;
