-- Switch to database
USE DATABASE ECOMM_DB;
USE SCHEMA ECOMM;

CREATE OR REPLACE FILE FORMAT MY_PARQUET_FORMAT
  TYPE = PARQUET;

CREATE OR REPLACE STAGE PARQUET_STAGE
    STORAGE_INTEGRATION = MY_GCS_INTEGRATION
    URL = 'gcs://bucket_ecomm/'
    FILE_FORMAT = MY_PARQUET_FORMAT;

-- Inspect Data Manually
LIST @PARQUET_STAGE;

SELECT *
FROM @PARQUET_STAGE/from_faker
(FILE_FORMAT => 'MY_PARQUET_FORMAT');