-- Switch to database
USE DATABASE ECOMM_DB;
USE SCHEMA ECOMM;

CREATE OR REPLACE TABLE EMAIL_ORDERS (
    CUSTOMER            VARCHAR(100),
    PRODUCT             VARCHAR(255),
    SKU                 VARCHAR(50),
    QTY                 INT,
    PRICE               VARCHAR(50),
    LINE_TOTAL          VARCHAR(50),
    TOTAL_AMOUNT        VARCHAR(50),
    PAYMENT_METHOD      VARCHAR(50),
    PAYMENT_REFERENCE   VARCHAR(50),
    ORDER_DATE          TIMESTAMP,
    PAYMENT_DATE        TIMESTAMP,
    EMAIL_TIMESTAMP     TIMESTAMP
);

CREATE OR REPLACE TABLE CUSTOMERS (
    ADDRESS_CITY        VARCHAR(50),
    ADDRESS_COMPANY     VARCHAR(100),
    ADDRESS_PROVINCE    VARCHAR(50),
    ADDRESS_ZIP         VARCHAR(50),
    EMAIL               VARCHAR(50),
    FIRST_NAME          VARCHAR(50),
    FULL_NAME           VARCHAR(50),
    LAST_NAME           VARCHAR(50),
    PHONE               VARCHAR(50)
);

CREATE OR REPLACE TABLE PRODUCTS (
    IMAGE_SRC           VARCHAR(500),
    PRODUCT_CATEGORY    VARCHAR(150),
    PRODUCT_DESCRIPTION VARCHAR(2000),
    PRODUCT_SKU         VARCHAR(20),
    TITLE               VARCHAR(150),
    UNIT_PRICE          FLOAT,
    VENDOR              VARCHAR(100)
);

CREATE OR REPLACE TABLE DATABASE_ORDERS (
    ROW_ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    ORDER_NUMBER        VARCHAR(50),
    ORDER_DATE          TIMESTAMP,
    BILLING_NAME        VARCHAR(100),
    LINEITEM_NAME       VARCHAR(255),
    LINEITEM_QTY        INT,
    PAYMENT_METHOD      VARCHAR(50),
    PAYMENT_REFERENCE   VARCHAR(50),
    PAYMENT_DATE        TIMESTAMP,
    FULFILLMENT_DATE    TIMESTAMP,
    EMAIL               VARCHAR(100),
    ADDRESS_COMPANY     VARCHAR(255),
    ADDRESS_CITY        VARCHAR(100),
    ADDRESS_PROVINCE    VARCHAR(100),
    ADDRESS_ZIP         VARCHAR(20),
    PHONE               VARCHAR(20),
    PRODUCT_SKU         VARCHAR(50),
    PRODUCT_DESCRIPTION VARCHAR(500),
    VENDOR              VARCHAR(100),
    PRODUCT_CATEGORY    VARCHAR(100),
    UNIT_PRICE          FLOAT,
    IMAGE_SRC           VARCHAR(500)
);

CREATE OR REPLACE TABLE PARQUET_ORDERS (
    ADDRESS_CITY           VARCHAR(100),
    ADDRESS_COMPANY        VARCHAR(255),
    ADDRESS_PROVINCE       VARCHAR(100),
    ADDRESS_ZIP            INT,
    BILLING_NAME           VARCHAR(100),
    EMAIL                  VARCHAR(100),
    FIRST_NAME             VARCHAR(50),
    FULFILLMENT_DATE       VARCHAR(50),
    IMAGE_SRC              VARCHAR(500),
    LAST_NAME              VARCHAR(50),
    LINEITEM_NAME          VARCHAR(500),
    LINEITEM_QTY           INT,
    ORDER_DATE             VARCHAR(50),
    ORDER_NUMBER           VARCHAR(50),
    PAYMENT_DATE           VARCHAR(50),
    PAYMENT_METHOD         VARCHAR(50),
    PAYMENT_REFERENCE      VARCHAR(50),
    PHONE                  VARCHAR(50),
    PRODUCT_CATEGORY       VARCHAR(100),
    PRODUCT_DESCRIPTION    VARCHAR(1000),
    PRODUCT_SKU            VARCHAR(50),
    UNIT_PRICE             FLOAT,
    VENDOR                 VARCHAR(100)
);